# Generated by Django 5.0.6 on 2024-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerurl',
            name='slug',
            field=models.TextField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='path',
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
