# Generated by Django 5.0.6 on 2024-05-31 15:26

import website.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_outerurl_slug_alter_shortenedurl_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'verbose_name': 'Переход', 'verbose_name_plural': 'Переходы'},
        ),
        migrations.AlterModelOptions(
            name='outerurl',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'verbose_name': 'Сокращенная ссылка', 'verbose_name_plural': 'Сокращенные ссылки'},
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='description',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='outerurl',
            name='slug',
            field=models.TextField(blank=True, max_length=256, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='outerurl',
            name='url',
            field=models.TextField(max_length=256, validators=[website.form_validators.validate_url], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='path',
            field=models.TextField(max_length=128, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
