version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python ./app/manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DEBUG=0
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123

  db:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
